@url=http://localhost:8080

################################################################################
# Request donation
################################################################################
POST {{url}}/api/v1/donations
Content-Type: application/json

{
  "donatorId": "someid01",
  "donateeId": "someid02",
  "cents": 240
}

################################################################################
# Check user 1
################################################################################
GET {{url}}/api/v1/users?id=someid01
Content-Type: application/json

################################################################################
# Check user 2
################################################################################
GET {{url}}/api/v1/users?id=someid02
Content-Type: application/json
