@url=http://localhost:8080

################################################################################
# Create user
################################################################################
POST {{url}}/api/v1/users
Content-Type: application/json

{
  "email": "foo@hexago.com",
  "nickname": "redshore",
  "givenName": "Suhyuk",
  "familyName": "Lee",
  "birthYear": 1993,
  "birthMonth": 9,
  "birthDay": 25
}

################################################################################
# Get user
################################################################################
GET {{url}}/api/v1/users?email=foo@bar.com
Content-Type: application/json

################################################################################
# Delete user
################################################################################
DELETE {{url}}/api/v1/users?email=foo@bar.com
Content-Type: application/json

################################################################################
# Request donation
################################################################################
POST {{url}}/api/v1/donations
Content-Type: application/json

{
  "donatorId": "foo@hexago.com",
  "donateeId": "bar@hexago.com",
  "cents": 240
}
