logger:
  format: text # text / json
  stackTrace: false
timeout:
  startup: 10 # seconds
  shutdown: 30 # seconds
server:
  http:
    host: '0.0.0.0'
    port: 8080
mongodb:
  addrs:
    - mongodb:27017
  database: hexago
  authSource: admin
  username: root
  password: root
  heartbeatInterval: 15000 # milliseconds
  maxConnectionPool: 50
kafka:
  addrs:
    - kafka1:59092
    - kafka2:59093
  topics:
    donationRequest:
      topic: donation-request
      username: user
      password: user
      maxRetry: 3
