logger:
  format: text # text / json
  stackTrace: false
timeout:
  startup: 10 # seconds
  shutdown: 30 # seconds
server:
  http:
    host: '0.0.0.0'
    port: 8080
mongodb:
  addrs:
    - localhost:27017
  database: hexago
  authSource: admin
  username: root
  password: root
  heartbeatInterval: 15000 # milliseconds
  maxConnectionPool: 50
kafka:
  addrs:
    - localhost:59092
    - localhost:59093
  topics:
    paymentRequest:
      topic: paymentRequest
      username: user
      password: user
      maxRetry: 3
