// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/isutare412/hexago/pkg/config"
	"github.com/isutare412/hexago/pkg/core/port"
	"github.com/isutare412/hexago/pkg/core/service/student"
	"github.com/isutare412/hexago/pkg/infrastructure/repo"
)

// Injectors from wire.go:

func dependencyInjection(ctx context.Context, cfg *config.Config) (*beans, error) {
	mongoDB, err := repo.NewMongoDB(ctx, cfg)
	if err != nil {
		return nil, err
	}
	studentService := student.NewService(mongoDB)
	mainBeans := &beans{
		mongoRepo: mongoDB,
		stuSvc:    studentService,
	}
	return mainBeans, nil
}

// wire.go:

type beans struct {
	mongoRepo *repo.MongoDB
	stuSvc    port.StudentService
}
