mode: development
mongodb:
  addrs:
    - localhost:27017
  database: hexago
  authSource: hexago
  username: hexagoer
  password: hexagoer
  heartbeatInterval: 15000 # milliseconds
  maxConnectionPool: 50
