// Package api GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/users": {
            "get": {
                "description": "Get an user.",
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "x-example": "foo@bar.com",
                        "description": "Contents provider id.",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.getUserResp"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/http.errorResp"
                        }
                    }
                }
            },
            "post": {
                "description": "Create an user.",
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "description": "Request to create user.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.createUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/http.errorResp"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an user.",
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "x-example": "foo@bar.com",
                        "description": "Contents provider id.",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/http.errorResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.createUserReq": {
            "type": "object",
            "properties": {
                "birthDay": {
                    "type": "integer",
                    "example": 25
                },
                "birthMonth": {
                    "type": "integer",
                    "example": 9
                },
                "birthYear": {
                    "type": "integer",
                    "example": 1993
                },
                "email": {
                    "type": "string",
                    "example": "foo@bar.com"
                },
                "familyName": {
                    "type": "string"
                },
                "givenName": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "http.errorResp": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "http.getUserResp": {
            "type": "object",
            "properties": {
                "birthDay": {
                    "type": "integer",
                    "example": 25
                },
                "birthMonth": {
                    "type": "integer",
                    "example": 9
                },
                "birthYear": {
                    "type": "integer",
                    "example": 1993
                },
                "email": {
                    "type": "string",
                    "example": "foo@bar.com"
                },
                "familyName": {
                    "type": "string"
                },
                "givenName": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Hexago API Gateway",
	Description:      "API gateway for Hexago project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
