// Package api GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/donations": {
            "post": {
                "description": "Request donation.",
                "tags": [
                    "Donation"
                ],
                "parameters": [
                    {
                        "description": "Donation request.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.requestDonationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/http.errorResp"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "description": "Get an user.",
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "x-example": "id001",
                        "description": "Id of user.",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.getUserResp"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/http.errorResp"
                        }
                    }
                }
            },
            "post": {
                "description": "Create an user.",
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "description": "Request to create user.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.createUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/http.errorResp"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an user.",
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "x-example": "id001",
                        "description": "Id of user.",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/http.errorResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.createUserReq": {
            "type": "object",
            "properties": {
                "birthDay": {
                    "type": "integer",
                    "example": 25
                },
                "birthMonth": {
                    "type": "integer",
                    "example": 9
                },
                "birthYear": {
                    "type": "integer",
                    "example": 1993
                },
                "email": {
                    "type": "string",
                    "example": "foo@bar.com"
                },
                "familyName": {
                    "type": "string"
                },
                "givenName": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "id001"
                },
                "middleName": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string",
                    "example": "redshore"
                }
            }
        },
        "http.donateRelation": {
            "type": "object",
            "properties": {
                "cents": {
                    "type": "integer",
                    "example": 120
                },
                "nickname": {
                    "type": "string",
                    "example": "redshore"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2022-05-05T06:22:40.328Z"
                },
                "userId": {
                    "type": "string",
                    "example": "id001"
                }
            }
        },
        "http.errorResp": {
            "type": "object",
            "properties": {
                "errorMsg": {
                    "type": "string"
                }
            }
        },
        "http.getUserResp": {
            "type": "object",
            "properties": {
                "birthDay": {
                    "type": "integer",
                    "example": 25
                },
                "birthMonth": {
                    "type": "integer",
                    "example": 9
                },
                "birthYear": {
                    "type": "integer",
                    "example": 1993
                },
                "donatedFrom": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.donateRelation"
                    }
                },
                "donatedTo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.donateRelation"
                    }
                },
                "email": {
                    "type": "string",
                    "example": "foo@bar.com"
                },
                "familyName": {
                    "type": "string"
                },
                "givenName": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "id001"
                },
                "middleName": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string",
                    "example": "redshore"
                }
            }
        },
        "http.requestDonationReq": {
            "type": "object",
            "properties": {
                "cents": {
                    "type": "integer",
                    "example": 150
                },
                "donateeId": {
                    "type": "string",
                    "example": "id002"
                },
                "donatorId": {
                    "type": "string",
                    "example": "id001"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Hexago API Gateway",
	Description:      "API gateway for Hexago project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
