definitions:
  http.createUserReq:
    properties:
      birthDay:
        example: 25
        type: integer
      birthMonth:
        example: 9
        type: integer
      birthYear:
        example: 1993
        type: integer
      email:
        example: foo@bar.com
        type: string
      familyName:
        type: string
      givenName:
        type: string
      id:
        example: id001
        type: string
      middleName:
        type: string
      nickname:
        example: redshore
        type: string
    type: object
  http.donateRelation:
    properties:
      cents:
        example: 120
        type: integer
      nickname:
        example: redshore
        type: string
      timestamp:
        example: "2022-05-05T06:22:40.328Z"
        type: string
      userId:
        example: id001
        type: string
    type: object
  http.errorResp:
    properties:
      errorMsg:
        type: string
    type: object
  http.getUserResp:
    properties:
      birthDay:
        example: 25
        type: integer
      birthMonth:
        example: 9
        type: integer
      birthYear:
        example: 1993
        type: integer
      donatedFrom:
        items:
          $ref: '#/definitions/http.donateRelation'
        type: array
      donatedTo:
        items:
          $ref: '#/definitions/http.donateRelation'
        type: array
      email:
        example: foo@bar.com
        type: string
      familyName:
        type: string
      givenName:
        type: string
      id:
        example: id001
        type: string
      middleName:
        type: string
      nickname:
        example: redshore
        type: string
    type: object
  http.requestDonationReq:
    properties:
      cents:
        example: 150
        type: integer
      donateeId:
        example: id002
        type: string
      donatorId:
        example: id001
        type: string
    type: object
info:
  contact: {}
  description: API gateway for Hexago project.
  title: Hexago API Gateway
  version: "0.1"
paths:
  /api/v1/donations:
    post:
      description: Request donation.
      parameters:
      - description: Donation request.
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.requestDonationReq'
      responses:
        "200":
          description: ""
        default:
          description: ""
          schema:
            $ref: '#/definitions/http.errorResp'
      tags:
      - Donation
  /api/v1/users:
    delete:
      description: Delete an user.
      parameters:
      - description: Id of user.
        in: query
        name: id
        required: true
        type: string
        x-example: id001
      responses:
        "200":
          description: ""
        default:
          description: ""
          schema:
            $ref: '#/definitions/http.errorResp'
      tags:
      - User
    get:
      description: Get an user.
      parameters:
      - description: Id of user.
        in: query
        name: id
        required: true
        type: string
        x-example: id001
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.getUserResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http.errorResp'
      tags:
      - User
    post:
      description: Create an user.
      parameters:
      - description: Request to create user.
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.createUserReq'
      responses:
        "200":
          description: ""
        default:
          description: ""
          schema:
            $ref: '#/definitions/http.errorResp'
      tags:
      - User
swagger: "2.0"
