logger:
  format: text # text / json
  stackTrace: false
timeout:
  startup: 10 # seconds
  shutdown: 30 # seconds
mongodb:
  addrs:
    - localhost:27017
  database: hexago
  authSource: admin
  username: root
  password: root
  heartbeatInterval: 15000 # milliseconds
  maxConnectionPool: 50
kafka:
  addrs:
    - localhost:59092
    - localhost:59093
  topics:
    donationRequest:
      topic: donation-request
      username: user
      password: user
      group: donation-request-payment
      timeout: 30 # seconds
