logger:
  format: text # text / json
  stackTrace: false
timeout:
  startup: 10 # seconds
  shutdown: 30 # seconds
mongodb:
  addrs:
    - localhost:27017
  database: hexago
  authSource: admin
  username: root
  password: root
  heartbeatInterval: 15000 # milliseconds
  maxConnectionPool: 50
